version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
    volumes:
      - .:/go/src/github.com/0xsequence/waas-authenticator
    environment:
      CONFIG: ./etc/docker.toml
    ports:
      - "9123:9123"

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5173
      - DYNAMODB_SHARE_DB=1
    volumes:
      - "../docker/awslocal_ready_hook.sh:/etc/localstack/init/ready.d/awslocal_ready_hook.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
