region = "us-east-2"

[service]
    mode = "dev"
    vsock = true
    use_nsm = true
    enclave_port = 5000
    proxy_port = 8000

[admin]
    public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCx1vYO1jq01ILTsL6wH76dN6rFWF5WebsxYv9Hx7QSa2/BIxLtIQgtNn0n/iJGu+cQv5nn6BJcVkP6JSYVV53LqsMqsm1/YqrZtT0S7Bniz3hZSpvs9Od6Vx1t6HRZgn6bUnsm2lu6BqQ0pFMrPwqGEn5HG42j4VtT5FwQ0o8G8HDYN8pOahfA/4WOpRGw9TzNokb7v5UFd9kUUqtH3FCsV/BHH7LaqFgs5dBqmsF3wsm3ZiLvkDg0+asZGw40L2c2HEVdD5DzOQqvcepN//kTf6wCGXhVYKt/B4RlycQjVYvIvBaMCUjlNwzPBhff8NpaBdZLvXgTio2jCGoq3oTmEBwziSx7ziqZMoSkqPZ4MTk7/2CrMzuB1f5UnS3Ek2enTkGUaqhU3iTKT+acFG1EqaGNtXNmvJ7og2ITSF08Y4E2g1vSmj7rRaXEUTKX4LkDZhA3GbL0wnvjGArSIXwbP/zHezPQwNP0JnrdoeSF3Xz8jMlxsUChAyhvogUISs= SequenceBuilder-dev"

[endpoints]
    metadata_server = "http://169.254.169.254"
    waas_api_server = "https://dev2-api.sequence.app"

[database]
    tenants_table = "WaasAuthenticatorNitroStackDev2-TenantsTableB701DC57-14X7METT7V19E"
    sessions_table = "WaasAuthenticatorNitroStackDev2-SessionsTable7C302024-1LOA9B0P4IDGI"

[kms]
    tenant_keys = ["arn:aws:kms:us-east-2:170768627592:key/08660469-f470-4bd9-ab37-fb5b5763e027"]
    default_session_keys = ["arn:aws:kms:us-east-2:170768627592:key/eec8d845-d69b-4b04-8d77-6f01c58002dd"]
    default_transport_keys = ["arn:aws:kms:us-east-2:170768627592:key/0fd8f803-9cb5-4de5-86e4-41963fb6043d"]
