region = "us-east-1"

[service]
    mode = "local"
    vsock = false
    use_nsm = false
    enclave_port = 9123
    proxy_port = 9124

[admin]
    public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCx1vYO1jq01ILTsL6wH76dN6rFWF5WebsxYv9Hx7QSa2/BIxLtIQgtNn0n/iJGu+cQv5nn6BJcVkP6JSYVV53LqsMqsm1/YqrZtT0S7Bniz3hZSpvs9Od6Vx1t6HRZgn6bUnsm2lu6BqQ0pFMrPwqGEn5HG42j4VtT5FwQ0o8G8HDYN8pOahfA/4WOpRGw9TzNokb7v5UFd9kUUqtH3FCsV/BHH7LaqFgs5dBqmsF3wsm3ZiLvkDg0+asZGw40L2c2HEVdD5DzOQqvcepN//kTf6wCGXhVYKt/B4RlycQjVYvIvBaMCUjlNwzPBhff8NpaBdZLvXgTio2jCGoq3oTmEBwziSx7ziqZMoSkqPZ4MTk7/2CrMzuB1f5UnS3Ek2enTkGUaqhU3iTKT+acFG1EqaGNtXNmvJ7og2ITSF08Y4E2g1vSmj7rRaXEUTKX4LkDZhA3GbL0wnvjGArSIXwbP/zHezPQwNP0JnrdoeSF3Xz8jMlxsUChAyhvogUISs= SequenceBuilder-dev"

[endpoints]
    aws_endpoint = "http://localstack:4566"
    waas_api_server = "http://host.docker.internal:4422"

[database]
    tenants_table = "TenantsTable"
    sessions_table = "SessionsTable"

[kms]
    tenant_keys = ["arn:aws:kms:us-east-1:000000000000:key/27ebbde0-49d2-4cb6-ad78-4f2c24fe7b79"]
    default_session_keys = ["arn:aws:kms:us-east-1:000000000000:key/27ebbde0-49d2-4cb6-ad78-4f2c24fe7b79"]
    default_transport_keys = ["arn:aws:kms:us-east-1:000000000000:key/aeb99e0f-9e89-44de-a084-e1817af47778"]
